CREATE DATABASE crudNodeMySql;

use crudNodeMySql;

CREATE TABLE customer {
    id INT(6) UNSIGNED AUTO-INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(15)
};

SHOW TABLES;

DESCRIBE customer;